image_types:
  - .png
  - .apng
  - .avif
  - .gif
  - .jpg
  - .jpeg
  - .jfif
  - .pjpeg
  - .pjp
  - .svg
  - .webp

ocr:
  dataset: /storage/brno2/home/xkavul01/datasets/iam
  type: lines
  cnn_model: vgg16_bn
  weights: /storage/brno2/home/xkavul01/base_ocr/ocr/vgg16_ctc_enhanced_log/models/model_239.pth
  weights_encoder: /storage/brno2/home/xkavul01/base_ocr/ocr/vgg16_ctc_shortcut_log/models/model_239.pth
  device: cuda
  save_dir: /storage/brno2/home/xkavul01/base_ocr/ocr/vgg16_ctc_enhanced_log
  n_epochs: 240
  batch_size: 16 # 32
  num_workers: 0
  fixed_height: 128
  fixed_width: 1792
  num_layers: 3
  decoder: ctc_enhanced
  learning_rate: 0.0001
  weight_decay: 0.00005
  dropout: 0.25
  decoder_loss: cross-entropy
  weight: 0.7
  encoder_freeze: false
  ignore_index: true
  mask: true
