image_types:
  - .png
  - .apng
  - .avif
  - .gif
  - .jpg
  - .jpeg
  - .jfif
  - .pjpeg
  - .pjp
  - .svg
  - .webp

ocr:
  dataset: /storage/brno2/home/xkavul01/datasets/iam
  type: lines
  cnn_model: vgg16_bn
  weights: /storage/brno2/home/xkavul01/base_ocr/ocr/vgg16_mp_ctc_log/models/model_180.pth
  weights_encoder: null
  device: cuda
  save_dir: /storage/brno2/home/xkavul01/base_ocr/ocr/vgg16_mp_ctc_log
  n_epochs: 240
  batch_size: 16
  num_workers: 0
  fixed_height: 128
  fixed_width: 1792
  num_layers: 3
  decoder: mp_ctc
  learning_rate: 0.001
  weight_decay: 0.00005
  dropout: 0.25
  weight: 0.7
  encoder_freeze: false
  mask: false
