image_types:
  - .png
  - .apng
  - .avif
  - .gif
  - .jpg
  - .jpeg
  - .jfif
  - .pjpeg
  - .pjp
  - .svg
  - .webp

sen:
  dataset: C:\Users\Danie\datasets\iam_sen
  weights: null
  device: cpu
  save_dir: C:\Users\Danie\PycharmProjects\diploma_thesis\sen\test_log
  n_epochs: 400
  batch_size: 2
  num_workers: 0
  max_height: 32
  learning_rate: 0.0005
  weight_decay: 0
